[env:pico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
upload_port = COM4
monitor_speed = 19200
build_src_filter = +<main.cpp> -<blinky.cpp>
build_flags =
  -D __FREERTOS=1
lib_deps =
  gin66/FastAccelStepper@^1.2.5

[env:pico2_blinky]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
upload_port = COM4
monitor_speed = 19200
build_src_filter = +<blinky.cpp> -<main.cpp>
